### ISSUE TITLE
.onion addresses for masternodes

### ISSUE THREAD

**Issue by DaMatrix** [piratecash/piratecash#12]
There's two main issues when trying to run a masternode using Tor over hidden service (i.e. a `.onion` address):

- [ ] The masternode isn't reachable by other nodes unless they have Tor enabled as well (obviously). But if we can't expect other nodes to be using Tor, why mention onion addresses at all in the masternode menu?
- [ ] v3 `.onion`s won't work with the current system. The problem isn't that the Tor version is outdated (I don't think so anyway) but rather that they're too big to be stored at all with the way PirateCash currently stores addresses.

![image](https://user-images.githubusercontent.com/11216106/51209004-733b9800-190f-11e9-8bf8-c50a56d1a49b.png)

**Comment by gades** [comment]
https://piratecash.net/en/site/masternode#hidden_service

<img width="969" alt="Screen Shot 2019-08-14 at 09 46 07" src="https://user-images.githubusercontent.com/4200730/63007661-c36cdf80-be89-11e9-8dc7-b18264e8a1c0.png">

**Comment by gades** [comment]
PirateCash does not support hidden service version 3 (ie. long onion addresses).
