### ISSUE TITLE
Major bugs since soft fork

### ISSUE THREAD

**Issue by DaMatrix** [piratecash/piratecash#14]
The following are major bugs that me and many others have been experiencing since the recent soft fork in v1.0.4, and have persisted in every version up to 1.0.4.7. Due to these bugs staking, running masternodes and just sending/receiving transactions is basically impossible.

- [ ] As soon as a proof-of-stake block is mined, the wallet will refuse to synchronize with the network. The newly minted block is never submitted to peers, and when the real chain catches up, it's not downloaded.  This results in a new chain being made that's only valid on the local wallet, and therefore the node is completely unusable until the data directory is deleted and the node has performed a full resync.
- [ ] While plain daemons running 1.0.4.7 are able to remain synced with the network (although blocks take much longer to be distributed than before), as soon as an address containing valid coins is imported, the daemon will stop synchronizing and become stuck at the current height. After a restart it'll start downloading blocks again, but then become stuck again once it's done.
- [ ] When a masternode is enabled on a daemon, the daemon will NEVER download blocks, even after a restart (as described above).

These are the major things that I've been able to reproduce multiple times on every version since the fork.  I'm still doing more testing, I think there's a correlation between synchronization getting stuck and `listen=1` being set.  If anyone has anything else that I didn't mention, comment it here and I'll add it if I can reproduce it.

**Comment by DaMatrix** [comment]
seems to be more or less fixed with latest releases.

**Comment by gades** [comment]
thanks for your report, one bug has been fixed on version 1.0.4.9-1.0.5.0. That's why we added option https://github.com/piratecash/piratecash/commit/e8070e86192b43de92723d53c9a52461562a505e 
After grace period is done then the processing blocks are work but don't accept to the chain. We will test this issue in testnet and then will back to the enable our patch.

**Comment by gades** [comment]
we just added workaround to the code but it is not fixed yet
