### ISSUE TITLE
the buttons are not visible at low resolution of the monitor

### ISSUE THREAD

**Issue by Barlend** [piratecash/piratecash#23]
at resolution 1024*600 critical information not visible
![photo_2020-02-13_01-21-52](https://user-images.githubusercontent.com/8507030/74386659-389c7b80-4dff-11ea-8ef8-8ef7991d7c24.jpg)

I guess the problem is in https://github.com/piratecash/piratecash/blob/master/src/qt/forms/overviewpage.ui
```
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>960</width>
    **<height>686</height>**
   </rect>
  </property>

```

**Comment by gades** [comment]
Thanks, new version v18 have different design
