### ISSUE TITLE
Updating Raspinode LCD screen

### ISSUE THREAD

**Issue by pkepler** [piratecash/piratecash#25]
The update available in the Raspinode makes the LCD monitoring go away.  Everything works on the node via terminal or SSH.  The Pi just displayed command line login query.

**Comment by gades** [comment]
did you try execute in CLI from root /var/www/raspinode/lcd.py  ? can you check cron task too ?

**Comment by pkepler** [comment]
No but I will execute it and let you know.  What is cron task?  How do I check it?

**Comment by gades** [comment]
Please check the file /etc/cron.d/lcd

**Comment by pkepler** [comment]
I get the following error message executing the cmd.  Am I doing it right?
<img width="426" alt="Screen Shot 2021-01-31 at 12 54 52 PM" src="https://user-images.githubusercontent.com/46732761/106393174-a13f8800-63c3-11eb-8cbb-4dcbba5b9916.png">

**Comment by gades** [comment]
please install pyfiglet module by execute from root 
pip install pyfiglet

**Comment by pkepler** [comment]
I attempted the above command and got this
<img width="554" alt="Screen Shot 2021-01-31 at 2 10 18 PM" src="https://user-images.githubusercontent.com/46732761/106395059-2039be00-63ce-11eb-9708-bf33e9caadf8.png">

Then I researched and found this cmd to install:
Step 1
sudo apt-get update -y
Step 2
sudo apt-get install -y python3-pyfiglet

This seemed to work.  So after install I tried your original cmd: "/var/www/raspinode/lcd.py"

This is the result:

<img width="571" alt="Screen Shot 2021-01-31 at 2 09 02 PM" src="https://user-images.githubusercontent.com/46732761/106395088-57a86a80-63ce-11eb-882c-c82465cc88a3.png">

**Comment by gades** [comment]
you need run /var/www/raspinode/lcd.py from user root (execute sudo bash or sudo /var/www/raspinode/lcd.py )

looks like python2 was removed from rasbian by EOS and installing python3-pyfiglet will fix your issue

**Comment by pkepler** [comment]
<img width="455" alt="Screen Shot 2021-01-31 at 2 19 37 PM" src="https://user-images.githubusercontent.com/46732761/106395274-5fb4da00-63cf-11eb-9f90-1c1e8354f0ef.png">

**Comment by pkepler** [comment]
![IMG_0279](https://user-images.githubusercontent.com/46732761/106399669-07d69d00-63e8-11eb-9991-27685317e771.JPG)
Success!  Thank you so much for your help.  Very fun project and I was going to leave it headless and stake the 10,000 but now I get to keep the LCD on.  I hope others find this thread.  Thanks again.

**Comment by pkepler** [comment]
How do I add the "/var/www/raspinode/lcd.py" so that it starts every time on reboot?

**Comment by gades** [comment]
It's automatically execute by cron from  /etc/cron.d/lcd, your issue was related to missing pyfiglet. We will check release and update iso.

Also, Did you check our bot software http://t.me/piratecash_bot ? there you can run free Masternodes

**Comment by pkepler** [comment]
It boots up without the monitoring screen,  but I run the "/var....." and it starts fine after I run that file.

I use the bot on Telegram, it's very nice.  You know the old "not your keys, not your coins..." though.

**Comment by gades** [comment]
please check cron task here /etc/cron.d/lcd
also, you can add cron task for user root
* * * * * /var/www/raspinode/lcd.py

**Comment by gades** [comment]
Fixed on latest update - please goto interface and install 0.11.11
